spring:
  main:
    allow-bean-definition-overriding: true
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    request-context-attribute: request
    prefer-file-system-access: false

server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /generator
